config/routes.rb
Cgl::Application.routes.draw do
 
  root :to => 'sessions#new'

  resources :items, :reports, :errors
  resources :sessions, only: [:new, :create, :index]
  resources :expeditions, only: [:index, :new, :create] do
    get :view, on: :collection
  end
  resources :users do
    get :view, on: :collection
  end
  resources :sendmen, only:[:index, :new, :show, :create] do
    get :view, on: :collection
    get :watch, on: :collection
  end
  resources :orders do
    get :copy, on: :member
  end
  post '*a', :to => 'sessions#new'
  get '*a', :to => 'sessions#new'

end

app/views/shared/_in_letters_head.erb
<table class="thead">
  <tr>
    <td class="id"> No </td>
    <td class="club"> Дата отправки </td>
    <td class="mail"> Отправитель </td>
    <td class="full"> Заголовок </td>
    <td class="status"> Статус</td>
    <td class="symbol">  <%= link_to 'Создать сообщение', new_sendman_path %></td>
  </tr>
</table>

app/views/shared/_items_body.erb
<table class="tbody">
  <% @items.each do |i|%>
      <tr>
        <td class="id"><%= i.id %></td>
        <td class="name"><%= i.name %></td>
        <td class="full"><%= i.full %></td>
        <td class="art"><%= i.art %></td>
        <td class="box"><%= i.box %></td>
        <td class="status"><%= i.status %></td>
        <td class="symbol"><%= link_to 'Просмотр', i %></td>
      </tr>
  <% end %>
</table>

app/views/shared/_items_head.erb
<table class="thead">
  <tr>
    <td class="id"> No </td>
    <td class="name"> Наименование </td>
    <td class="full"> Полное </td>
    <td class="art"> Артикул </td>
    <td class="box"> Шт. </td>
    <td class="status"> Статус</td>
    <td class="symbol"> <%= link_to 'Новое изделие', new_item_path %></td>
  </tr>
</table>

app/views/shared/_logs_body.erb
<table class="tbody">
  <% @log_sessions.each do |i|%>
      <tr>
        <td class="status"><%= i.id %></td>
        <td class="art"><%= i.user_id %></td>
        <td class="name"><%= i.name_user(@users_name) %></td>
        <td class="full"><%= i.created_at %></td>
        <td class="art"><%= i.ip_addr %></td>
      </tr>
  <% end %>
</table>

app/views/shared/_logs_head.erb
<table class="thead">
  <tr>
    <td class="status"> No </td>
    <td class="art"> id пользователя </td>
    <td class="name"> Имя пользователя </td>
    <td class="full"> дата,время входа в систему </td>
    <td class="art">  ip адрес</td>
  </tr>
</table>

app/views/shared/_mail_form.erb
<%= form_for @order do |o| %>
    <% if action_name=='new'%>
        <%= o.hidden_field(:user_id, :value => current_user[:id] ) %>
        <%= o.hidden_field(:region, :value => current_user[:region] ) %>
        <%= o.hidden_field(:q_box, :value => 0 ) %>
    <% end %>
    <div class="page_header">
        Дата исполнения: <%= o.date_field( :deliver_at, :value => Date.tomorrow, min: Date.tomorrow, :max => Date.today + 7.days)%><br/>
        Состав заказа:
    </div>
    <div class="page_nav">
        <ul>
        <% if action_name=='new'%>
            <li class="button"><%= link_to'Отменить', orders_path%></li>
        <% else %>
            <li class="button"><%= link_to'Отменить', order_path(@order)%></li>
        <% end %>
        <li class="button"> <%= o.submit 'Сохранить заказ'%> </li>
        </ul>
    </div>
    <div id="orderShow">
       <%= render :partial => 'shared/order_head'%>
       <div class="tbodylong">
          <table>
              <% k =0 %>
              <% @lots.each do |i|%>
                  <% if i.item %>
                    <tr style="background-color: <%= i.item.bg_color %>">
                        <td class="name"><%= i.item[:name] %></td>
                        <td class="art"><%= i.item[:art] %></td>
                        <td class="name"><%= i.item[:box] %></td>
                        <td class="name">
                          <%= o.fields_for 'lots_attributes', :index => k do |l|%>
                              <% if i.item.is_active %>
                                  <% if action_name =='edit' %>
                                    <%= l.hidden_field(:id, :value=>i.id )  %>
                                  <% end %>
                                  <%= l.hidden_field(:item_id, :value=>i.item_id ) %>
                                  <%= l.text_field :quantity, :value=> i.quantity, size: Q_FIELD  %>
                              <% else %>
                                  <% k-=1; %>
                                  Недоступно
                              <% end %>
                          <% end %>
                        </td>
                    </tr>
                    <% k+=1 %>
                  <% end %>
              <% end %>
          </table>
       </div>
    </div>
<%end%>

app/views/shared/_mail_form.haml
.page_header
  Заголовок:
  Текст сообщения:
  .page_nav
    %ul
    %li {class:'button'}
      = link_to'Отменить', sendmen_path
    %li {class:'button'}
#orderShow

app/views/shared/_main_menu.erb
<ul class="menu">
  <li class="<%=visible_for(EXPEDITOR)%>"><%= link_to 'Заказы', expeditions_path %></li>
  <li class="<%=visible_for(USER)%>"><%= link_to 'Новый заказ', new_order_path %></li>
  <li class="<%=visible_for(USER+ADMIN+TESTER)%>"><%= link_to 'Заказы', orders_path %></li>
  <li class="<%=visible_for(ADMIN+TESTER)%>"><%= link_to 'Доставка', expeditions_path %></li>
  <li class="<%=visible_for(EXPEDITOR+ADMIN+TESTER)%>"><%= link_to 'Отгрузки', controller: 'expeditions',action: 'view' %></li>
  <li class="<%=visible_for(ADMIN+TESTER)%>"><%= link_to 'Изделия', items_path %></li>
  <li class="<%=visible_for(ALL)%>"><%= link_to 'Сообщения', sendmen_path %></li>
  <li class="<%=visible_for(ADMIN)%>"><%= link_to 'Все сообщения', watch_sendmen_path %></li>
  <li class="<%=visible_for(ADMIN+TESTER)%>"><%= link_to 'Логи сессий', action: 'view', controller: 'users'%></li>
  <li class="<%=visible_for(ADMIN+TESTER)%>"><%= link_to 'Админка', users_path %></li>
  <li class="<%=visible_for(ALL)%>"><%= link_to 'Выход', sessions_path %></li>
</ul>

app/views/shared/_order_head.erb
<table class="thead">
  <tr>
    <td class="name"> Наименование </td>
    <td class="art"> Артикул </td>
    <td class="name"> Штук в коробке </td>
    <td class="name"> Заказанное количество коробок </td>
  </tr>
</table>

app/views/shared/_orders_head.erb
<table class="thead">
  <tr>
    <td class="status"> No </td>
    <td class="date"> Дата исполнения </td>
    <td class="full"> Получатель </td>
    <td class="art"> Кол-во мест </td>
    <td class="art"> Статус </td>
    <td class="symbol"> <%= link_to 'Новый заказ', new_order_path %> </td>
  </tr>
</table>

app/views/shared/_out_letters_body.erb
<table class="tbody">
  <% @out_letters.each do |u|%>
      <tr>
        <td class="id"><%= u.id %></td>
        <td class="club"><%= u.created_at %></td>
        <td class="mail"><%= u.name_user(@users_name) %></td>
        <td class="full"><%= u.comment %></td>
        <td class="status"><%= u.status %></td>
        <td class="symbol"><%= link_to 'Просмотр', u %></td>
  <% end %>
</table>

app/views/shared/_out_letters_head.erb
<table class="thead">
  <tr>
    <td class="id"> No </td>
    <td class="club"> Дата отправки </td>
    <td class="mail"> Получатель </td>
    <td class="full"> Заголовок </td>
    <td class="status"> Статус</td>
    <td class="symbol"> <%= link_to 'Создать сообщение', new_sendman_path%></td>
  </tr>
</table>

app/views/shared/_users_body.erb
<table class="tbody">
    <% @users.each do |u|%>
    <tr>
      <td class="id"><%= u.id %></td>
      <td class="mail"><%= u.email %></td>
      <td class="club"><%= u.name %></td>
      <td class="status"><%= u.type_owner %></td>
      <td class="addr"><%= u.address %></td>
      <td class="status"><%= u.region %></td>
      <td class="status"><%= u.status %></td>
      <td class="symbol"><%= link_to 'Просмотр', u %></td>
    <% end %>
</table>

app/views/shared/_users_head.erb
<table class="thead">
  <tr>
    <td class="id"> No </td>
    <td class="mail"> E-mail </td>
    <td class="club"> Имя </td>
    <td class="status"> Тип </td>
    <td class="addr"> Адрес </td>
    <td class="status"> Маршрут</td>
    <td class="status"> Статус</td>
    <td class="symbol"> <%= link_to 'Новый пользователь', new_user_path %></td>
  </tr>
</table>