config/routes.rb
Cgl::Application.routes.draw do
 
  root :to => 'sessions#new'

  resources :items, :reports, :errors
  resources :sessions, only: [:new, :create, :index]
  resources :expeditions, only: [:index, :new, :create] do
    get :view, on: :collection
  end
  resources :users do
    get :view, on: :collection
  end
  resources :sendmen, only:[:index, :new, :show, :create] do
    get :view, on: :collection
    get :watch, on: :collection
  end
  resources :orders do
    get :copy, on: :member
  end
  post '*a', :to => 'sessions#new'
  get '*a', :to => 'sessions#new'

end

app/models/expedition.rb
class Expedition < ActiveRecord::Base

  belongs_to :user
  has_many :loadups, dependent: :destroy
  accepts_nested_attributes_for :loadups, allow_destroy: true

  include MakeStringOrderExpedition
  include MakeString
  include SomeClassMethod

  def is_active
    !self.updated_at.to_date.past?
  end

  def change_status
    self.is_active ?  Date.yesterday : Date.today
  end

  def change_obj_status
    self.updated_at= self.change_status
  end

  def in_time?
    date = self[:updated_at].to_date
    date == self[:take_aboard].to_date ? 'В срок': date
  end
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
  respond_to :html, :json, :xml
  include MakeXlsx

  before_action :check_expeditor
  before_filter :check_tester, only: [:create]
  before_filter :make_active_date,  only: [:index, :new, :create]
  before_filter :take_orders,       only: [:index, :new]
  before_filter :prepare_user_names, only: [:index, :new]
  before_filter :make_shipment_docs,only: [:create]

  def index
    flsh('Время приема заказов не закончилось!') unless @active_date.today?
    flsh(ALERT_STRING) unless @orders
    respond_with @active_date, @orders, @users_name
  end

  def new
    go_to('index',ALERT_STRING) unless make_new_waybill
    redirect_to expeditions_path unless @orders || @orders.empty?
    respond_with @orders, @users_name, @waybill
  end

  def view
    take_waybills
    go_back(ALERT_STRING) unless @waybills
    respond_with @waybills
  end

  def create
    redirect_to action: 'view'
  end

  private

# before filter - Оформление документов на отгрузку.
# Выполняется, как одна транзакция, для соблюдения целостности базы.
# Имеет смысл только пакет документов целиком.
# Передается дата отгрузки.
  def make_shipment_docs
    Order.transaction do
      begin
        raise unless (@waybill = current_user.expeditions.create(expedition_params))
        raise unless current_user.update_orders_status(Date.today,@active_date)
        raise unless (@orders = current_user.take_orders_delivered(Date.today, @active_date).includes(:lots))
        raise unless make_waybill_docs( @waybill, @orders)
        raise unless current_user.email_shipping_docs(@waybill, @orders)
        flash[:notice] ='Отгрузка оформлена успешно!'
      rescue
        raise ActiveRecord::Rollback, flash[:notice] = 'Отгрузка не прошла! ' + ALERT_STRING
      end
    end
  end

  # before filter - готовит новую огрузку на дату, считает содержимое заказов включенных в отгрузку
  def make_new_waybill
    (@items = Item.count_items_amount(@orders)) && (@waybill = current_user.new_waybill(@active_date, @items))
  end

# before filter - готовит список отгрузок по данному экспедитору
  def take_waybills
    @waybills = Expedition.get_for_user(current_user).order('take_aboard DESC, updated_at DESC')
  end

# before filter - готовит список неотгруженных заказов delivered: nil на дату отгрузки, вместе с содержимым
  def take_orders
    @orders = current_user.take_orders_delivered(nil,@active_date).includes(:lots)
  end

# before filter - вычисляет текущую дату отгузки,
  def make_active_date
    @active_date = (DateTime.now + TIME_X.hour).to_date
  end

  # без коментариев, см. /view/expeditions/new.html.erb
  def expedition_params
    params.require(:expedition).permit(:user_id, :take_aboard, :region, :delivered, :amount_boxes, loadups_attributes:[:item_id, :user_id, :quantity, :q_box, :take_aboard, :region])
  end

end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper

end

app/views/expeditions/index.html.erb
<div class="page_header">
  <h1>K отгрузке заказов: <%= @orders.size %>.</h1>
  Дата отгрузки: <%=@active_date%> <br/>
  Маршрут No <%=current_user[:region]%>; <br/>
  Экспедитор (имя, ID): <%=current_user[:name]%>, <%=current_user[:id]%>;
</div>
<div class="page_nav">
  <ul>
    <li class="button"> <%= link_to 'Посмотреть отгрузки', action: 'view' %> </li>
    <li class="button"> <%= link_to_if( @active_date.today? &&!(@orders.nil? || @orders.empty?),'Сформировать отгрузку', new_expedition_path )%></li>
  </ul>
</div>
<div id="orderInExShow">
    <% if @orders.nil? || @orders.empty?  %>
        <h2>Нет в базе заказов на отгрузку по вашему маршруту!</h2>
    <% else%>
        <%= render partial: 'shared/expedition_header', locals: { orders: @orders, users_name: @users_name} %>
    <% end %>
</div>

app/views/expeditions/new.html.erb
<div class="page_header">
<h2> Дата отгрузки: <%= @waybill[:take_aboard]%></h2>
   Маршрут No <%=current_user[:region]%>; <br/>
   Экспедитор (имя, ID): <%=current_user[:name]%>, <%=current_user[:id]%>;
  <h2>K отгрузке: <%= @orders.size %> заказов.</h2>
</div>
<%= form_for @waybill do |w| %>
    <div class="page_nav" >
      <ul>
      <li class="button"> <%= link_to 'Посмотреть отгрузки', action: 'view' %> </li>
      <li class="button"><%= link_to 'Отменить', action: 'index' %></li>
      <li class="button"> <%= w.submit 'Сохранить отгрузку'%> </li>
          </ul>
    </div>
    <div id="orderInExShow">
        <%= render partial: 'shared/expedition_header' %>
    </div>
    <%= w.hidden_field(:user_id, :value=> @waybill[:user_id] ) %>
    <%= w.hidden_field(:take_aboard, :value=> @waybill[:take_aboard] ) %>
    <%= w.hidden_field(:region, :value=> @waybill[:region] ) %>
    <%= w.hidden_field(:delivered, :value=> Date.today ) %>
    <%= w.hidden_field(:amount_boxes, :value=> @waybill[:amount_boxes] ) %>
    <div id="orderShow">
        <h2> Готовим накладную на получение изделий и накладные на доставку </h2>
        <%= render partial: 'shared/order_head' %>
        <div class="tbodyshort">
          <table class="tbodyw">
                <% k=0 %>
                <% @items.each do |i|%>
                    <tr>
                        <td class="name"><%= i.name %></td>
                        <td class="art"><%= i.art %></td>
                        <td class="name"><%= i.box %></td>
                        <td class="name"><%= i.technic %></td>
                        <%= w.fields_for 'loadups_attributes', :index => k do |l|%>
                            <%= l.hidden_field(:item_id, :value => i.id ) %>
                            <%= l.hidden_field(:user_id, :value => @waybill[:user_id] ) %>
                            <%= l.hidden_field(:quantity, :value => i.technic ) %>
                            <%= l.hidden_field(:q_box, :value => i.box ) %>
                            <%= l.hidden_field(:take_aboard, :value => Date.today ) %>
                            <%= l.hidden_field(:region, :value => @waybill[:region] ) %>
                        <% end %>
                    </tr>
                    <% k+=1 %>
                <% end %>
                <% if @items.size< TBODY_SHORT %>
                    <%= render :partial => 'shared/item_footer', locals: {:waybill => @waybill}%>
                <% end %>
          </table>
        </div>
        <% unless @items.size< TBODY_SHORT %>
            <div class="thead">
              <table class="thead">
                <%= render :partial => 'shared/item_footer', locals: {:waybill => @waybill}%>
              </table>
            </div>
        <% end %>
    </div>
<%end%>

app/views/expeditions/view.html.erb
<div class="page_header">
  <h1>Список последних отгрузок</h1>
  Экспедитор (имя, ID): <%=current_user[:name]%>, <%=current_user[:id]%>
</div>
<div class="page_nav">
  <ul>
  <li class="button"><%= link_to 'Заказы к отгрузке', action: 'index' %></li>
      </ul>
</div>
<div id="expShow">
    <% if @waybills.empty? %>
        <b> Нет в базе ваших отгрузок! </b>
    <% else%>
        <div class="thead">
            <table class="thead">
               <tr>
                    <td class="status"> No накл.</td>
                    <td class="status"> Маршрут </td>
                    <td class="date"> Заказано на </td>
                    <td class="date"> Отгружено </td>
                    <td class="date"> Количество мест </td>
                    <td class="art"> Статус </td>
               </tr>
            </table>
        </div>
        <div class="tbodylong">
            <table class="tbodyw">
                <% @waybills.each do |i|%>
                <tr>
                    <td class="status"><%= i.id %></td>
                    <td class="status"><%= i.region %></td>
                    <td class="date"><%= i.take_aboard %></td>
                    <td class="date"><%= i.in_time? %></td>
                    <td class="date"><%= i.amount_boxes %></td>
                    <td class="art"><%= i.name_status %></td>
                </tr>
                <% end %>
            </table>
        </div>
    <% end %>
</div>